require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
RSpec/MultipleExpectations:
  Max: 2
Layout/LineLength:
  Max: 160
Metrics/AbcSize:
  Max: 25
Metrics/MethodLength:
  Max: 30
