require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-hc
Style/Documentation:
  Enabled: false
AllCops:
  NewCops: enable
RSpec/MultipleExpectations:
  Max: 2
Layout/LineLength:
  Max: 160
Metrics/AbcSize:
  Max: 36
Metrics/MethodLength:
  Max: 35
Metrics/BlockLength:
  Exclude:
    - "config/environments/*"
Hc/RailsSpecificActionName:
  Exclude:
    - app/controllers/api/v1/omniauth_callbacks_controller.rb
    - app/controllers/api/v1/users_controller.rb
RSpec/ExampleLength:
  Exclude:
    - spec/requests/api/v1/tweets_spec.rb
